---
# Enable or disable WinRM
winrm_configuration_enable: true

# WinRM service start mode: auto or delayed
winrm_configuration_start_mode: auto

# Optionally block WinRM HTTP port if using HTTPS
# NB. Kerberos and NTLM encrypt traffic with HTTP
winrm_configuration_http_block: false

# Enable WinRM HTTPS listener, creates a self-signed
# cert if WinRM HTTPS listener is not yet configured
winrm_configuration_https_enable: false

# WinRM service configuration
# CBT is None, Relaxed, or Strict
winrm_configuration_service_config:
  AllowUnencrypted: false
  Auth:
    Basic: false
    Kerberos: true
    Negotiate: true
    Certificate: false
    CredSSP: false
    CbtHardeningLevel: Relaxed
  IPv4Filter: '*'
  IPv6Filter: '*'

# Firewall profiles to apply rules
winrm_configuration_firewall_profiles:
  - domain
  - private

# Optionally display current configuration
winrm_configuration_display_config: false
