---
# Enable or disable WinRM
winrm_configuration_enable: true

# By default Basic / HTTPS connections
# will be enabled using a self-signed
# certificate in case the winrm HTTPS
# listener has not been configured yet.
# Disable this to skip configuring winrm
winrm_configuration_https_enable: true

# Optionally ensure WinRM HTTP port is blocked
winrm_configuration_http_block: true

# winrm service start mode: auto or delayed
winrm_configuration_start_mode: auto

# Firewall profiles to apply rules
winrm_configuration_firewall_profiles:
  - domain
  - private

# Optionally display current configuration
winrm_configuration_display_config: false
