---
- name: Check services to disable
  ansible.windows.win_service_info:
    name: "{{ item }}"
  register: disable_services
  loop: "{{ service_enablement_disable | select }}"

- name: Disable unwanted services
  ansible.windows.win_service:
    name: "{{ item.item }}"
    state: stopped
    start_mode: disabled
  loop: "{{ disable_services.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.exists

- name: Check services to enable
  ansible.windows.win_service_info:
    name: "{{ item }}"
  register: enable_services
  loop: "{{ service_enablement_enable | select }}"

- name: Enable wanted services
  ansible.windows.win_service:
    name: "{{ item.item }}"
    state: started
    start_mode: auto
  loop: "{{ enable_services.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.exists
