---
- name: Configure Windows
  hosts: all
  become: false
  gather_facts: false
  collections:
    - myllynen.windows_ansible_roles
  vars:
    #
    # Ansible WinRM configuration
    #
    ansible_connection: winrm
    ansible_pipelining: true
    ansible_winrm_port: 5986
    ansible_winrm_scheme: https
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

    ansible_winrm_user: winrm
    ansible_winrm_password: Foobar_12

    ansible_become_method: runas

    #
    # Ansible Windows/SSH configuration
    #
    #ansible_shell_type: powershell
    #ansible_become_method: runas

    #
    # accounts_local
    #
    # Enable or disable built-in Administrator
    accounts_local_administrator_enable: true

    # Enable or disable Ansible user password expiration
    accounts_local_ansible_user_password_expires: false

    # Show or hide Ansible user on Welcome Screen
    accounts_local_ansible_user_show_on_welcome: false

    #
    # boot_configuration
    #
    boot_configuration_timeout: 30

    #
    # dns_client
    #
    # Target network adapters
    dns_client_adapter_names: '*'

    # List of DNS servers
    dns_client_dns_servers:
    #  - 1.1.1.1
    #  - 8.8.8.8

    #
    # dotnet_optimize
    #
    # Compile PowerShell assemblies
    dotnet_optimize_powershell: true

    # Compile all installed assemblies
    dotnet_optimize_all_assemblies: false

    #
    # etc_hosts
    #
    #etc_hosts_header: - omitted here for brevity

    # Add entry for host itself based on Ansible facts
    # This will use the first IP address found in system
    # This should be disabled when not using static IP
    etc_hosts_self_add: false

    # Force domain name used in host self entry
    # If unset defaults to ansible_facts.domain
    # Required if ansible_facts.domain is empty
    etc_hosts_self_domain:

    # List of lines to add to /etc/hosts
    # NB. Other entries will be removed
    etc_hosts_entries:
    #  - 192.168.122.1    gateway.example.com gateway
    #  - 192.168.122.150  bastion.example.com bastion

    # /etc/hosts entries to omit
    # none - do not omit entries
    # ipv4 - omit all IPv4 entries
    # ipv6 - omit all IPv6 entries
    etc_hosts_omit_entries: none

    #
    # network_configuration
    #
    # Enable or disable IPv6
    network_configuration_ipv6_enable: true

    # Enable or disable NetBIOS
    network_configuration_netbios_enable: true

    # Reboot after network changes
    network_configuration_reboot: true

    #
    # performance_tuning
    #
    # NTFS Last Access Time updates
    ntfs_last_access_time_update: false

    # Page file size configuration
    # auto      - automatically managed
    # disabled  - page file disabled
    # size      - static page file size in MB
    page_file_size: auto
    page_file_disk: C

    # Reboot after page file change
    page_file_reboot: true

    # Power scheme configuration
    # balanced          - balance between performance and energy use
    # power_saver       - max energy savings at the cost of performance
    # high_performance  - maximum performance with higher energy use
    power_scheme: high_performance

    #
    # rdp_configuration
    #
    # Enable or disable RDP
    rdp_configuration_enable: true

    # Firewall profiles to apply rules
    rdp_configuration_firewall_profiles:
      - domain
      - private

    # Require authentication for RDP
    rdp_configuration_authenticate: true

    #
    # services_enablement
    #
    service_enablement_disable:
      - WbioSrvc

    service_enablement_enable:

    #
    # service_recovery_options
    #
    service_recovery_options:
      - name: SNMPTRAP
        actions:
          - delay_ms: 30000
            type: restart
          - delay_ms: 30000
            type: restart
          - delay_ms: 60000
            type: reboot

    #
    # sshd_configuration
    #
    # Enable or disable sshd
    sshd_configuration_enable: true

    # Install OpenSSH.Server capability if needed
    # Skipping this will speedup the role a little
    # if sshd is already installed but the role is
    # going to fail in case sshd is not installed.
    # This is not needed with Windows Server 2025.
    sshd_configuration_install: false

    # Default shell for sshd, this must be kept in
    # sync with ansible_shell_type to avoid errors
    # NB. Needs an absolute path
    # For cmd.exe the path is: C:\Windows\System32\cmd.exe
    # For PowerShell must use: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    sshd_configuration_shell:

    # Administrators SSH keys to add/remove
    sshd_configuration_admins_keys:
    #  absent:
    #    - ssh-rsa ... id_rsa.pub
    #  present:
    #    - ssh-ed25519 ... id_ed25519.pub

    # sshd service start mode: auto or delayed
    sshd_configuration_start_mode: auto

    # Firewall profiles to apply rules
    sshd_configuration_firewall_profiles:
      - domain
      - private
      - public

    # Enable sshd_config validatiion using a copy if
    # the file is about to be updated. Recommended.
    sshd_configuration_config_validate: true

    # sshd configuration file template to use
    # This is mutually exclusive with the options below
    # Role provided alternatives:
    # * default_config - OpenSSH.Server 0.0.1.0 default
    sshd_configuration_config_file:

    # These options will be explicitly set in sshd_config,
    # no other options will be left in place after update.
    # The example set below matches OpenSSH.Server 0.0.1.0
    sshd_configuration_options:
    #  AuthorizedKeysFile: .ssh/authorized_keys
    #  Subsystem: sftp sftp-server.exe
    #  AllowGroups: administrators "openssh users"
    #  Match Group administrators:
    #    - AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

    #
    # system_hostname
    #
    # System hostname to be configured in the system
    #
    # Should be short name (not FQDN) and valid for DNS
    system_hostname: "{{ ansible_facts.hostname | upper }}"

    # Reboot after system hostname change
    system_hostname_reboot: true

    #
    # system_init
    #
    # Log system initialization message on a fresh system

    # System initialization file
    system_init_file: C:\Windows\init_info_system.txt

    # System initialization message
    system_init_msg_file: "This system was initialized by system_init on {{ '%Y-%m-%d %H:%M:%S %Z' | strftime }}.\r\n"
    system_init_msg_log: "{{ system_init_msg_file }}"

    # Actions to take after initialization
    # reboot - reboot after initialization
    # syslog - write message to system log
    system_init_final_actions:
      - syslog

    #
    # system_locale
    #
    # NB. Configuring keyboard for Welcome Screen is notoriously difficult, this
    # role may or may not work reliably and may need more than round to apply ok
    #
    # NB. This role is currently at most experimental and probably should not be used!

    # https://docs.microsoft.com/windows/win32/intl/table-of-geographical-locations
    system_locale_location: 77

    system_locale_system: en-US
    system_locale_ui: en-US
    system_locale_user: en-US
    system_locale_input: 0409:0000040B

    #
    # system_reboot
    #
    system_reboot_timeout: 600.0

    system_reboot_delay_pre: 2.0
    system_reboot_delay_post: 0.0

    system_reboot_message: Reboot initiated by Ansible

    #
    # system_time
    #
    system_time_ntp_servers:
      - time.windows.com

    system_time_timezone: FLE Standard Time

    # Reboot after timezone change
    system_time_timezone_reboot: true

    #
    # system_update
    #
    # Parameters for win_updates
    system_update_categories: '*'
    system_update_state: installed

    # Display update results
    system_update_display_results: true

    # Reboot if needed after updates
    system_update_reboot: true
    system_update_reboot_timeout: 1200

    # Compile all installed assemblies
    # This will happen only after updates
    system_update_compile_assemblies: true

    # Trigger compilation only when updates with
    # the following description were part of the
    # installed updates. Use '.*' for everything.
    system_update_compile_filter: Cumulative Update

    #
    # user_experience
    #
    # Open Server Manager at logon
    user_experience_server_manager_at_logon: true

    # Enable or disable new network location wizard
    user_experience_network_location_wizard: false

    # Show or hide last user name on Welcome Screen
    user_experience_show_last_user_name: true

    #
    # windows_recovery
    #
    # Enable or disable Windows Recovery Environment
    windows_recovery_enable: false

    #
    # winrm_configuration
    #
    # Enable or disable WinRM
    winrm_configuration_enable: true

    # By default Basic / HTTPS connections
    # will be enabled using a self-signed
    # certificate in case the winrm HTTPS
    # listener has not been configured yet.
    # Disable this to skip configuring winrm
    winrm_configuration_https_enable: true

    # Optionally ensure WinRM HTTP port is blocked
    winrm_configuration_http_block: true

    # winrm service start mode: auto or delayed
    winrm_configuration_start_mode: auto

    # Firewall profiles to apply rules
    winrm_configuration_firewall_profiles:
      - domain
      - private
      - public

    # Optionally display current configuration
    winrm_configuration_display_config: false

  roles:
    - dotnet_optimize
    - system_hostname
    - etc_hosts
    - dns_client
    - system_time
    ##- system_update
    #- system_locale
    - accounts_local
    - boot_configuration
    - network_configuration
    - winrm_configuration
    - sshd_configuration
    - rdp_configuration
    #- windows_recovery
    - performance_tuning
    #- service_enablement
    #- service_recovery
    - user_experience
    #- system_reboot
    - system_init
