---

- hosts: localhost
  become: true
  no_log: true
  tasks:
    - name: Debug credential
      ansible.builtin.debug:
        msg: "Debugging credentials from environment var {{ lookup('env', 'SN_PASSWORD') }}"