---
namespace: myllynen
name: windows_ansible_roles
version: "4.3.2"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible roles for Windows configuration.
license:
  - GPL-3.0-or-later
tags:
  - windows
  - configuration
  - infrastructure
dependencies:
  ansible.windows: ">=2.5.0"
  community.windows: ">=2.3.0"
repository: https://www.github.com/myllynen/windows-ansible-roles
issues: https://www.github.com/myllynen/windows-ansible-roles/issues
