---
- name: Disable IPv6 on all interfaces
  community.windows.win_net_adapter_feature:
    state: disabled
    interface: '*'
    component_id:
      - ms_tcpip6
  when: network_configuration_ipv6_disable | bool
