---
- name: Check system status
  ansible.windows.win_stat:
    path: "{{ system_init_file }}"
  register: system_init

- name: Initialize fresh system
  ansible.builtin.include_tasks: init.yml
  when: not system_init.stat.exists
