---
- name: Disable WSL
  ansible.builtin.include_tasks: disable.yml
  when:
    - wsl_configuration_enable is not none
    - not wsl_configuration_enable | bool

- name: Enable WSL
  ansible.builtin.include_tasks: enable.yml
  when:
    - wsl_configuration_enable is not none
    - wsl_configuration_enable | bool
