---
- name: Verify DSC settings format
  assert:
    that:
      - "'setting' in item"
      - "'resource_name' in item"
      - "'parameters' in item"
    fail_msg: |
      Invalid or incomplete DSC setting:

      {{ item | to_nice_yaml }}
    quiet: true
  loop: "{{ dsc_settings | select }}"
  loop_control:
    label: "{{ item.setting }}"

# Set inject_facts_as_vars = False to avoid warnings
- name: Apply DSC settings
  ansible.windows.win_dsc:
    resource_name: "{{ item.resource_name }}"
    args: "{{ item.parameters }}"
  register: dsc_config
  loop: "{{ dsc_settings | select }}"
  loop_control:
    label: "{{ item.setting }}"

- name: Reboot system
  vars:
    reboot_needed: "{{ dsc_config.results
                       | selectattr('item.reboot', 'defined')
                       | selectattr('item.reboot', 'equalto', true)
                       | selectattr('changed', 'equalto', true) | length > 0 }}"
  ansible.windows.win_reboot:
    reboot_timeout: 600
    msg: "Ansible reboot after DSC changes"
  when:
    - dsc_settings_reboot | bool
    - dsc_config is changed
    - reboot_needed
