---
- name: Gather needed facts
  ansible.windows.setup:
    gather_subset:
      - '!all'
      - '!min'
      - user
  when: ansible_facts.user_id is not defined

- name: Fail if Administrator trying to disable own account
  fail:
    msg: "Refusing to disable Administrator own account."
  when:
    - not accounts_local_administrator_enable | bool
    - "'administrator' == ansible_facts.user_id | lower"

- name: Disable built-in Administrator account
  ansible.windows.win_user:
    name: Administrator
    account_disabled: true
  when: not accounts_local_administrator_enable | bool

- name: Enable built-in Administrator account
  ansible.windows.win_user:
    name: Administrator
    account_disabled: false
  when: accounts_local_administrator_enable | bool

- name: Configure password expiration for Ansible user
  ansible.windows.win_user:
    name: "{{ ansible_facts.user_id }}"
    password_never_expires: "{{ not accounts_local_ansible_user_password_expires | bool }}"

- name: Configure showing Ansible user in Welcome Screen
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList
    name: "{{ ansible_facts.user_id }}"
    type: DWord
    data: "{{ 1 if accounts_local_ansible_user_hide_in_welcome | bool else 0 }}"
