---
- name: Disable RDP service
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    type: DWord
    data: 1
  when: not rdp_configuration_enable | bool

- name: Block firewall RDP port
  community.windows.win_firewall_rule:
    name: Remote Desktop - User Mode (TCP-In)
    state: present
    enabled: true
    action: block
    direction: in
    localport: 3389
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"
  when: not rdp_configuration_enable | bool

- name: Configure RDP user authentication
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-TCP
    name: UserAuthentication
    type: DWord
    data: "{{ 1 if rdp_configuration_authenticate | bool else 0 }}"

- name: Enable RDP service
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    type: DWord
    data: 0
  when: rdp_configuration_enable | bool

- name: Allow firewall RDP port
  community.windows.win_firewall_rule:
    name: Remote Desktop - User Mode (TCP-In)
    state: present
    enabled: true
    action: allow
    direction: in
    localport: 3389
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"
  when: rdp_configuration_enable | bool
