---
# Compile PowerShell assemblies
dotnet_optimize_powershell: true

# Compile all assemblies as needed
dotnet_optimize_all_assemblies: false

# Force recompiling all assemblies
dotnet_optimize_force_recompile: false
