---
- name: Fail if trying to disable WinRM using WinRM
  ansible.builtin.fail:
    msg: "Refusing to disable WinRM when using WinRM."
  when: ansible_connection == 'winrm' or
        ansible_connection == 'psrp'

- name: Check WinRM service
  ansible.windows.win_service_info:
    name: WinRM
  register: winrm_service

- name: Disable WinRM service
  ansible.windows.win_service:
    name: WinRM
    state: stopped
    start_mode: disabled
  when: winrm_service.exists

- name: Block firewall WinRM HTTP port
  community.windows.win_firewall_rule:
    name: Windows Remote Management (HTTP-In)
    state: present
    enabled: true
    action: block
    direction: in
    localport: 5985
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"

- name: Block firewall WinRM HTTPS port
  community.windows.win_firewall_rule:
    name: Windows Remote Management (HTTPS-In)
    state: present
    enabled: true
    action: block
    direction: in
    localport: 5986
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"
