---
- name: Enable winrm service
  ansible.windows.win_service:
    state: started
    name: winrm
    start_mode: "{{ winrm_configuration_start_mode }}"

- name: Configure winrm service
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      $Ansible.Changed = $false
      $friendlyName = 'WinRM over HTTPS'
      $cert = Get-ChildItem -Path Cert:\LocalMachine\My | ? FriendlyName -eq $friendlyName
      $listener = Get-ChildItem -Path WSMan:\localhost\Listener -Recurse | ? Keys -contains 'Transport=HTTPS'
      if (-not $cert -and -not $listener) {
        $Ansible.Changed = $true
        $cert = New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My `
                  -DnsName $env:COMPUTERNAME -NotAfter (get-date).AddYears(10) `
                  -Provider 'Microsoft Enhanced RSA and AES Cryptographic Provider' `
                  -KeyLength 4096
        $cert.FriendlyName = $friendlyName
        New-Item -Path WSMan:\localhost\Listener -Transport HTTPS `
          -Address * -CertificateThumbPrint $cert.Thumbprint -Force
        Set-Item -Path WSMan:\localhost\Service\AllowUnencrypted -Value $false
        Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true
      }
  when: winrm_configuration_https_enable | bool

- name: Allow firewall WinRM HTTPS port
  community.windows.win_firewall_rule:
    enabled: true
    state: present
    name: Windows Remote Management (HTTPS-In)
    localport: 5986
    action: allow
    direction: in
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"
  when: winrm_configuration_https_enable | bool

- name: Block firewall WinRM HTTP port
  community.windows.win_firewall_rule:
    enabled: true
    state: present
    name: Windows Remote Management (HTTP-In)
    localport: 5985
    action: block
    direction: in
    protocol: tcp
    profiles: "{{ winrm_configuration_firewall_profiles | default(omit, true) }}"
  when: winrm_configuration_http_block | bool

- name: Display WinRM configuration
  include_tasks: display.yml
  when: winrm_configuration_display_config | bool
