---
- name: Disable WinRM
  ansible.builtin.include_tasks: disable.yml
  when: not winrm_configuration_enable | bool

- name: Enable WinRM
  ansible.builtin.include_tasks: enable.yml
  when: winrm_configuration_enable | bool
