---
- name: Disable Server Manager at logon
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\ServerManager
    name: DoNotOpenServerManagerAtLogon
    type: dword
    data: 1
  when: user_experience_server_manager_disable | bool

- name: Disable network location wizard
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Network\NewNetworkWindowOff
  when: user_experience_network_location_wizard_disable | bool
