---
- name: Check Windows Recovery Environment configuration
  win_command: reagentc /info
  register: winre_info
  changed_when: false

- name: Configure Windows Recovery Environment
  vars:
    winre_disable: "{{ '$true' if windows_recovery_disable|bool else '$false' }}"
    winre_enabled: "{{ '$true' if 'Enabled' in winre_info.stdout else '$false' }}"
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      $Ansible.Changed = $false
      if ({{ winre_disable }} -eq $true -and {{ winre_enabled }} -eq $true) {
        $Ansible.Changed = $true
        reagentc /disable
      }
      if ({{ winre_disable }} -eq $true -and (Test-Path -Path 'C:\Recovery')) {
        $Ansible.Changed = $true
        Remove-Item -Path 'C:\Recovery' -Recurse -Force
      }
      #if ({{ winre_disable }} -eq $true -and (Test-Path -Path 'C:\$WinREAgent')) {
      #  $Ansible.Changed = $true
      #  Remove-Item -Path 'C:\$WinREAgent' -Recurse -Force
      #}
      if ({{ winre_disable }} -eq $false -and {{ winre_enabled }} -eq $false) {
        $Ansible.Changed = $true
        reagentc /enable
      }
