---
# NTFS Last Access Time updates
ntfs_last_access_time_update: false

# Page file size configuration
# auto      - automatically managed
# disabled  - page file disabled
# size      - static page file size in MB
page_file_size: auto
page_file_disk: C

# Reboot after page file change
page_file_reboot: true

# Power scheme configuration
# balanced          - balance between performance and energy use
# power_saver       - max energy savings at the cost of performance
# high_performance  - maximum performance with higher energy use
power_scheme: balanced
