---
# Page file size configuration
# auto - automatically managed
# disabled - page file disabled
# size - static page file size in MB
page_file_size: auto
page_file_disk: C

# Reboot after page file change
page_file_reboot: true
