---
- name: Include tasks to install updates
  include_tasks:
    file: update.yml
  loop: "{{ range(1, system_update_retry_count | int + 1) }}"
  loop_control:
    loop_var: update_attempt

- name: Display update results
  debug:
    var: update_install
  when: system_update_display_results | bool

- name: Fail if updating did not succeed
  fail:
    msg: "Failed to install updates."
  when: update_install is failed

- name: Include role to compile assemblies
  vars:
    filter: "{{ system_update_compile_filter }}"
    filtered: "{{ update_install.updates | dict2items | selectattr('value.title', 'regex', filter) | length }}"
    dotnet_optimize_powershell: true
    dotnet_optimize_all_assemblies: true
  include_role:
    name: dotnet_optimize
  when:
    - system_update_compile_assemblies | bool
    - filtered | int > 0
