---
- name: Install updates
  vars:
    ansible_winrm_read_timeout_sec: "{{ system_update_reboot_timeout | int + 10 }}"
    ansible_winrm_operation_timeout_sec: "{{ system_update_reboot_timeout | int + 5 }}"
  ansible.windows.win_updates:
    category_names: "{{ system_update_categories }}"
    state: "{{ system_update_state }}"
    reboot: false
  register: update_install

- name: Display update results
  ansible.builtin.debug:
    var: update_install
  when: system_update_display_results | bool

- name: Reboot system
  ansible.windows.win_reboot:
    reboot_timeout: "{{ system_update_reboot_timeout | float }}"
    msg: "Ansible reboot after installing updates"
  register: reboot_status
  when:
    - system_update_reboot | bool
    - update_install.reboot_required

- name: Include role to compile assemblies
  vars:
    filter: "{{ system_update_compile_filter }}"
    filtered: "{{ update_install.updates | dict2items | selectattr('value.title', 'regex', filter) | length }}"
    dotnet_optimize_powershell: true
    dotnet_optimize_all_assemblies: true
  ansible.builtin.include_role:
    name: dotnet_optimize
  when:
    - system_update_compile_assemblies | bool
    - filtered | int > 0
