---
- name: Install all updates
  vars:
    ansible_winrm_read_timeout_sec: "{{ system_update_reboot_timeout|int + 10 }}"
    ansible_winrm_operation_timeout_sec: "{{ system_update_reboot_timeout|int + 5 }}"
  ansible.windows.win_updates:
    category_names: '*'
    state: installed
    reboot: true
    reboot_timeout: "{{ system_update_reboot_timeout|int }}"
  register: update_install

- name: Display update results
  ansible.builtin.debug:
    var: update_install

- name: Reboot system
  ansible.windows.win_reboot:
    pre_reboot_delay: 0
    reboot_timeout: "{{ system_update_reboot_timeout|int }}"
    msg: "Reboot after installing updates"
  when: update_install.reboot_required
