---
- name: Install updates
  vars:
    ansible_winrm_read_timeout_sec: "{{ system_update_reboot_timeout | int + 10 }}"
    ansible_winrm_operation_timeout_sec: "{{ system_update_reboot_timeout | int + 5 }}"
  ansible.windows.win_updates:
    category_names: "{{ system_update_categories }}"
    accept_list: "{{ system_update_accept_list | default(omit, true) }}"
    reject_list: "{{ system_update_reject_list | default(omit, true) }}"
    skip_optional: "{{ system_update_skip_optional | bool }}"
    state: "{{ system_update_state }}"
    reboot: false
  register: update_result
  ignore_errors: true
  when: >
    update_install is not defined or
    update_install is failed or
    (update_install is changed and
     system_update_retry_after_install | bool)

- name: Record update installation result
  set_fact:
    update_install: "{{ update_result }}"
    update_combined: "{{ update_combined | default({'updates': {}}) |
                         combine({'updates': update_result.updates}, recursive=true) }}"
  when: update_result is not skipped

- name: Reboot system
  ansible.windows.win_reboot:
    reboot_timeout: "{{ system_update_reboot_timeout | float }}"
    msg: "Ansible reboot after installing updates"
  register: reboot_status
  when:
    - system_update_reboot | bool
    - update_result is not skipped
    - update_install.reboot_required or
      (update_install is failed and
       update_attempt < system_update_retry_count | int)

- name: Record reboot status
  set_fact:
    system_update_rebooted: true
  when: reboot_status is not skipped

- name: Pause before next update attempt
  pause:
    seconds: "{{ system_update_retry_delay }}"
  when:
    - update_install is failed or
      (update_install is changed and
       system_update_retry_after_install | bool)
    - update_attempt < system_update_retry_count | int
