---
# Parameters for win_updates
system_update_categories: '*'
system_update_state: installed

# Display update results
system_update_display_results: true

# Reboot if needed after updates
system_update_reboot: true
system_update_reboot_timeout: 1200

# Compile all installed assemblies
# This will happen only after updates
system_update_compile_assemblies: true

# Trigger compilation only when updates with
# the following description were part of the
# installed updates. Use '.*' for everything.
system_update_compile_filter: Cumulative Update
