---
# Retry attempts and delay between retries
# for applying updates in case of failures
system_update_retry_count: 1
system_update_retry_delay: 30

# Retry applying updates also if updates were
# installed, subject to the above retry count
system_update_retry_after_install: true

# Parameters for win_updates
system_update_categories: '*'
system_update_accept_list: []
system_update_reject_list: []
system_update_skip_optional: true
system_update_state: installed

# Display update results, full or compact
system_update_display_results: true
system_update_display_results_full: true

# Reboot if needed after updates
system_update_reboot: true
system_update_reboot_timeout: 1200

# Compile all installed assemblies
# This will happen only after updates
system_update_compile_assemblies: true

# Trigger compilation only when updates with
# the following description were part of the
# installed updates. Use '.*' for everything.
system_update_compile_filter: Cumulative Update
