---
- name: Compile PowerShell assemblies
  check_mode: false
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      $Ansible.Changed = $false
      # From https://docs.ansible.com/ansible/latest/os_guide/windows_performance.html
      $ngenPath = [System.IO.Path]::Combine([Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory(), `
                                            'ngen.exe')
      [AppDomain]::CurrentDomain.GetAssemblies() | % {
        if (-not $_.Location) { continue }
        $name = Split-Path -Path $_.Location -Leaf
        if ($name.StartsWith('Microsoft.PowerShell')) {
          $images = & $ngenPath display $_.Location /nologo
          if ($images -match 'pending' -or
              $images -match 'not installed') {
            $Ansible.Changed = $true
            if ('{{ ansible_check_mode }}' -eq 'true') { Exit 0 }
            & $ngenPath install $_.Location /nologo
          }
        }
      }
  when: dotnet_optimize_powershell | bool

- name: Compile all installed assemblies
  community.windows.win_dotnet_ngen:
  when: dotnet_optimize_all_assemblies | bool
