---
- name: Compile PowerShell assemblies
  ansible.windows.win_powershell:
    error_action: continue
    script: |
      # From https://docs.ansible.com/ansible/latest/user_guide/windows_performance.html
      $env:path = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
      [AppDomain]::CurrentDomain.GetAssemblies() | % {
        if (!$_.location) { continue }
        $Name = Split-Path $_.location -leaf
        if ($Name.startswith("Microsoft.PowerShell")) {
          ngen install $_.location /nologo
        }
      }
  register: ngen_command
  changed_when: ngen_command.output[0] != "All compilation targets are up to date." or
                ngen_command.output | unique | length > 1
  when: dotnet_optimize_powershell | bool

- name: Compile all installed assemblies
  community.windows.win_dotnet_ngen:
  when: dotnet_optimize_all_assemblies | bool
