---
- name: Compile PowerShell assemblies
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      $Ansible.Changed = $false
      # From https://docs.ansible.com/ansible/latest/os_guide/windows_performance.html
      $ngenPath = [System.IO.Path]::Combine([Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory(), `
                                            'ngen.exe')
      [AppDomain]::CurrentDomain.GetAssemblies() | % {
        if (-not $_.Location) { continue }
        $name = Split-Path -Path $_.Location -Leaf
        if ($name.StartsWith('Microsoft.PowerShell')) {
          $res = & $ngenPath install $_.Location /nologo
          if ($res.Contains('Compiling assembly')) {
            $Ansible.Changed = $true
          }
        }
      }
  when: dotnet_optimize_powershell | bool

- name: Compile all installed assemblies
  community.windows.win_dotnet_ngen:
  when: dotnet_optimize_all_assemblies | bool
