---
- name: Compile PowerShell assemblies
  ansible.windows.win_powershell:
    error_action: continue
    script: |
      # From https://docs.ansible.com/ansible/latest/os_guide/windows_performance.html
      $ngenPath = [System.IO.Path]::Combine([Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory(), `
                                            'ngen.exe')
      [AppDomain]::CurrentDomain.GetAssemblies() | % {
        if (-not $_.Location) { continue }
        $name = Split-Path -Path $_.Location -Leaf
        if ($name.StartsWith('Microsoft.PowerShell')) {
          & $ngenPath install $_.Location /nologo
        }
      }
  register: ngen_command
  changed_when: ngen_command.output[0] != "All compilation targets are up to date." or
                ngen_command.output | unique | length > 1
  when: dotnet_optimize_powershell | bool

- name: Compile all installed assemblies
  community.windows.win_dotnet_ngen:
  when: dotnet_optimize_all_assemblies | bool
