galaxy_info:
  role_name: system_locale
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: system_locale role
  license: GPLv3+
  min_ansible_version: 2.11
  platforms:
    - name: Windows
      versions:
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - configuration
dependencies: []
