---
# Enable or disable RDP
rdp_configuration_enable: true

# Firewall profiles to apply rules
rdp_configuration_firewall_profiles:
  - domain
  - private

# Require authentication for RDP
rdp_configuration_authenticate: true
