---
# NB. Configuring keyboard for Welcome Screen is notoriously difficult, this
# role may or may not work reliably and may need more than round to apply ok

# https://docs.microsoft.com/windows/win32/intl/table-of-geographical-locations
system_locale_location: 244

system_locale_system: en-US
system_locale_ui: en-US
system_locale_user: en-US
system_locale_input: en-US
