---
- name: Fail if trying to disable sshd using SSH
  fail:
    msg: "Refusing to disable sshd when using SSH."
  when: ansible_connection == 'ssh'

- name: Check sshd service
  ansible.windows.win_service_info:
    name: sshd
  register: sshd_service

- name: Disable sshd service
  ansible.windows.win_service:
    name: sshd
    state: stopped
    start_mode: disabled
  when: sshd_service.exists

- name: Block firewall SSH port
  community.windows.win_firewall_rule:
    name: OpenSSH SSH Server (sshd)
    state: present
    enabled: true
    action: block
    direction: in
    localport: 22
    protocol: tcp
    profiles: "{{ sshd_configuration_firewall_profiles | default(omit, true) }}"
