---
- name: Disable sshd
  ansible.builtin.include_tasks: disable.yml
  when: not sshd_configuration_enable | bool

- name: Enable sshd
  ansible.builtin.include_tasks: enable.yml
  when: sshd_configuration_enable | bool
